# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_lhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Project'),
            preserve_default=False,
        ),
        # https://stackoverflow.com/questions/41623515/received-valueerror-found-wrong-number-0-of-constraints-for-during-djan
        migrations.AlterUniqueTogether(
            name='workload',
            unique_together=set([('dbms', 'hardware', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together=set([('cpu', 'memory', 'storage', 'storage_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'project', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinedata',
            unique_together=set([('pipeline_run', 'task_type', 'workload')]),
        ),
    ]
